// Backgrounds
Italianmarble=()=>{
    document.getElementById("background").style.backgroundColor="#e1dad2"
}
tailwind=()=>{
    document.getElementById("background").style.backgroundColor="#e8e8e4"
}
HazelCream=()=>{
    document.getElementById("background").style.backgroundColor="#e4dddc"
}
Sailaway=()=>{
    document.getElementById("background").style.backgroundColor="#dde9ea"
}
DogwoodBlossom=()=>{
    document.getElementById("background").style.backgroundColor="#fdc8d1"
}
Wonderlake=()=>{
    document.getElementById("background").style.backgroundColor="#60c6c6"
}
white=()=>{
    document.getElementById("background").style.backgroundColor="white"
}
Mint=()=>{
    document.getElementById("background").style.backgroundColor="#ADEFD1FF"
}
Silver=()=>{
    document.getElementById("background").style.backgroundColor="#A2A2A1FF"
}
// Pallete
IrishGlory=()=>{
    document.getElementById("colorPallete").style.backgroundColor="#74cabf"
}
Meanderinggarden=()=>{
    document.getElementById("colorPallete").style.backgroundColor="#90dec2"
}
Irisheyes=()=>{
    document.getElementById("colorPallete").style.backgroundColor="#ade8d0"
}
SkyBlue=()=>{
    document.getElementById("colorPallete").style.backgroundColor="#89ABE3FF"
}
TurkishSea=()=>{
    document.getElementById("colorPallete").style.backgroundColor="#195190FF"
}
